package libraryManagementSystemPro;


/**
 *
 * @author Wamique
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        newStudentButton = new javax.swing.JButton();
        newBookButton = new javax.swing.JButton();
        issueBookButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.setFocusable(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 150, 51));

        newStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddUser.png"))); // NOI18N
        newStudentButton.setText("New Student");
        newStudentButton.setFocusable(false);
        newStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 51));

        newBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AddBook.png"))); // NOI18N
        newBookButton.setText("New Book");
        newBookButton.setFocusable(false);
        newBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 51));

        issueBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/issue.png"))); // NOI18N
        issueBookButton.setText("Issue Book");
        issueBookButton.setFocusable(false);
        issueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(issueBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 170, 51));

        statisticsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Statics.png"))); // NOI18N
        statisticsButton.setText("Statistics");
        statisticsButton.setFocusable(false);
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(statisticsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 160, 51));

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Return Book.png"))); // NOI18N
        returnButton.setText("Return Book");
        returnButton.setFocusable(false);
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 180, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, 2150, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookButtonActionPerformed
        setEnabled(false);
        new NewBook(this).setVisible(true);
    }//GEN-LAST:event_newBookButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void newStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentButtonActionPerformed
        setEnabled(false);
        new NewStudent(this).setVisible(true);
    }//GEN-LAST:event_newStudentButtonActionPerformed

    private void issueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookButtonActionPerformed
        setEnabled(false);
        new Issue(this).setVisible(true);
    }//GEN-LAST:event_issueBookButtonActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        setEnabled(false);
        new Statistics(this).setVisible(true);
    }//GEN-LAST:event_statisticsButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        setEnabled(false);
        new Return(this).setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton issueBookButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton newBookButton;
    private javax.swing.JButton newStudentButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton statisticsButton;
    // End of variables declaration//GEN-END:variables
}
