package libraryManagementSystemPro;

import Project.ConnectionProvider;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Wamique
 */
public class Issue extends javax.swing.JFrame {

    /**
     * Creates new form Issue
     */
    
    private Home homeFrame;
    
    public Issue(Home homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        studentIDField = new javax.swing.JTextField();
        bookIDField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dueDateChooser = new com.toedter.calendar.JDateChooser();
        issueDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.setFocusable(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/X.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setFocusable(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        studentIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(studentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 260, -1));

        bookIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(bookIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));
        getContentPane().add(dueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 260, -1));
        getContentPane().add(issueDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Panel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        homeFrame.setEnabled(true);
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String bookID = bookIDField.getText();
        String studentID = studentIDField.getText();
        String issueDate = dateFormat.format(issueDateChooser.getDate());
        String dueDate = dateFormat.format(dueDateChooser.getDate());
        String returnBook = "No";        
        
        try{
            Connection conn = ConnectionProvider.getCon();
            Statement statement = conn.createStatement();
            ResultSet bookIDResultSet = statement.executeQuery("SELECT * FROM book WHERE bookID = '"+bookID+"'");
            if(bookIDResultSet.next()){
                ResultSet studentIDResultSet = statement.executeQuery("SELECT * FROM student WHERE studentID = '"+studentID+"'");
                if(studentIDResultSet.next()){
                    statement.executeUpdate("INSERT INTO issue VALUES('"+bookID+"','"+studentID+"','"+issueDate+"','"+dueDate+"','"+returnBook+"')");
                    JOptionPane.showMessageDialog(null, "Book Issued Successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                    homeFrame.setEnabled(true);
                    dispose();
                    new Issue(homeFrame).setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Student ID Not Found.", "Unsuccessful", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Book ID Not Found.", "Unsuccessful", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Book Already Issued", "Unsuccessful", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIDField;
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser dueDateChooser;
    private com.toedter.calendar.JDateChooser issueDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
