package libraryManagementSystemPro;

import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Wamique
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    
    private Home homeFrame;
    
    public Return(Home homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bookIDField = new javax.swing.JTextField();
        issueDateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        dueDateField = new javax.swing.JTextField();
        studentIDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        bookIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(bookIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 260, -1));

        issueDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(issueDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Due Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save.png"))); // NOI18N
        submitButton.setText("Submit");
        submitButton.setFocusable(false);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setFocusable(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        cancelButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/X.png"))); // NOI18N
        cancelButton1.setText("Cancel");
        cancelButton1.setFocusable(false);
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        dueDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(dueDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 260, -1));

        studentIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(studentIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Panel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
       homeFrame.setEnabled(true);
       setVisible(false);
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String bookID = bookIDField.getText();
        String studentID = studentIDField.getText();
        try{
            Connection conn = ConnectionProvider.getCon();
            Statement st = conn.createStatement();
            ResultSet resultSet = st.executeQuery("SELECT * FROM issue WHERE bookID ='"+bookID+"' AND studentID ='"+studentID+"'");
            if(resultSet.next()){
                // Pasting value of Issue Date and Due date
                issueDateField.setText(resultSet.getString(3));
                dueDateField.setText(resultSet.getString(4));

                // Enable Return Button
                submitButton.setEnabled(true);

            }else{
                JOptionPane.showMessageDialog(null,
                "Book is not issued to this Student.",
                "Failed",
                JOptionPane.ERROR_MESSAGE);
            }
        }catch (Exception f){
            JOptionPane.showMessageDialog(null,
            "Connection Error ",
            "Failed",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String bookID = bookIDField.getText();
        String studentID = studentIDField.getText();
        try{
            Connection conn = ConnectionProvider.getCon();
            Statement st = conn.createStatement();
            st.executeUpdate("UPDATE issue SET returnBook='YES' WHERE studentID='"+studentID+"' AND bookID='"+bookID+"'");
            
            JOptionPane.showMessageDialog(null,
                "Successful ",
                "Book Returned. ",
                JOptionPane.INFORMATION_MESSAGE);
            
            JOptionPane.showMessageDialog(null, "Book Returned Successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
            homeFrame.setEnabled(true);
            dispose();
            new Return(homeFrame).setVisible(true);
            
        }catch (Exception f){
            JOptionPane.showMessageDialog(null,
                "Connection Error ",
                "Failed",
                JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_submitButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIDField;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JTextField dueDateField;
    private javax.swing.JTextField issueDateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
